### ISSUE TITLE
Erreur de segmentation lors d'une génération d'images MNT 1 canal float32

### ISSUE THREAD

**Issue by XavDmz** [rok4/generation#3]
# Résumé

Une génération d'images 1 canal avec un typage float32 échoue presque instantanément lors de l'exécution de mergeNtiff, car une erreur de segmentation se produit.

# Détails

Je suis parti d'une image docker basée sur ubuntu:20.04 dans laquelle j'ai installé par apt les paquets suivants, téléchargés depuis les pages de releases des dépôts github du projet rok4 :

* librok4-base-1.1.0-ubuntu-20.04-amd64.deb
* librok4-core-perl-1.0.2-ubuntu-20.04-all.deb
* rok4-generation-4.1.4-ubuntu-20.04-amd64.deb
* rok4-pregeneration-4.2.1-ubuntu-20.04-all.deb
* rok4-styles-4.1-linux-all.deb
* rok4-tilematrixsets-4.1-linux-all.deb

Les images sources sont les images MNT issues du jeu de données [RGEALTI_2-0_1M_ASC_LAMB93-IGN69_D014_2023-01-03](https://wxs.ign.fr/9u5z4x13jqu05fb3o9cux5e1/telechargement/prepackage/RGEALTI-1M_PACK_FXX_2023-01-27$RGEALTI_2-0_1M_ASC_LAMB93-IGN69_D014_2023-01-03/file/RGEALTI_2-0_1M_ASC_LAMB93-IGN69_D014_2023-01-03.7z) de l'IGN, converties au format GeoTIFF à l'aide la commande suivant sous GDAL 2.2.3 :

```bash
gdal_translate -ot "Float32" -of "GTiff" "image_asc" "image_tiff"
```

Lors de l'exécution docker , les uids et gid de l'utilisateur hôte étaient utilisés, à l'aide de `docker run -u="$(id -u):$(id -g)"`. Lle fichier de configuration de prégénération, et les données sources, étaient fournis à l'aide de l'option "volume bind" de docker. il en est de même pour les dossiers de destination de l'espace de travail des outils de (pré)génération, comme des pyramides en sortie.

Les commandes lancées dans le conteneur étaient `be4.pl --conf=/tmp/config/be4.conf` puis `bash /tmp/rok4/scripts/main.sh`.
Je vais joindre la configuration be4 en commentaire.

Dans les journaux de `LEVEL_8_SCRIPT_1.sh`, aprè tous les avertissements de la libtiff sur les tags GeoTIFF, les seules entrées sont :

```txt
/tmp/rok4/scripts/LEVEL_8_SCRIPT_1.sh: line 129:    17 Segmentation fault      (core dumped) mergeNtiff -f ${MNT_CONF_DIR}/$config -r ${TMP_DIR}/ ${MERGENTIFF_OPTIONS}
/tmp/rok4/scripts/LEVEL_8_SCRIPT_1.sh : Erreur a la ligne 139
```

Après le plantage, `/tmp/rok4/share` contient bien les fichiers desconfiguration de decimateNtiff et mergeNtiff, ainsi que l'ébauche du fchier `.list`. `/tmp/rok4/tmp/LEVEL_8_SCRIPT_1` contient l'image TIFF partiellement remplie, contenant seulement `4949 2a00 0000 0000 ` quand ouverte dans un éditeur de texte. (L'en-tête TIFF, je suppose ?).

**Comment by XavDmz** [comment]
# Configuration be4 utilisée

```json
{
    "logger": {
        "level": "DEBUG",
        "layout": "%5p : %m (%M) %n"
    },
    "datasources": [
        {
            "top": "0",
            "bottom": "<AUTO>",
            "source": {
                "type": "IMAGES",
                "directory": "/data/RGEALTI",
                "srs": "IGNF:LAMB93"
            }
        }
    ],
    "pyramid": {
        "type": "GENERATION",
        "name": "RGEALTI_1M_D014_MNT",
        "compression": "zip",
        "tms": "LAMB93_1M_MNT.json",
        "storage": {
            "type": "FILE",
            "root": "/data/rok4/PYRAMIDS"
        },
        "nodata": [-99999],
        "pixel": {
            "sampleformat": "FLOAT32",
            "samplesperpixel": 1
        },
        "interpolation": "linear"
    },
    "process": {
        "directories": {
            "scripts": "/tmp/rok4/scripts",
            "local_tmp": "/tmp/rok4/tmp",
            "shared_tmp": "/tmp/rok4/share"
        },
        "parallelization": 1,
        "style": "/usr/share/rok4/styles/normal.json",
        "nodata": [-99999]
    }
}
```

**Comment by lowzonenose** [comment]
@XavDmz Il est possible de me fournir la commande **mergeNTiff** qui échoue avec les dalles et les options en entrée afin que je fasse du **profiling** sur le _Segmentation Fault_ ?

**Comment by lowzonenose** [comment]
En reprenant les paramètres ci dessus, nous avons la sortie de **debug** sur le **Segmentation Fault** :
```
work2cache version 4.1.0
warning	PixelConverter doesn't handle float samples
error	Cannot add converter to the input FileImage
```

**Comment by lowzonenose** [comment]
Ok, on est sur un problème de configuration.
On retire le style pour ce type de données !!!

**Comment by lowzonenose** [comment]
https://github.com/rok4/docker/issues/2
